#!/usr/bin/env bash
sudo apt -y update

if ! command -v git &> /dev/null; then
    sudo apt -y install git
fi

if [ ! -d $HOME/personal ]; then
    mkdir $HOME/personal
fi

git clone https://github.com/ThePrimeagen/dev-prod-2-example $HOME/personal/dev-prod-2-example

pushd $HOME/personal/dev-prod-2-example
./run
popd


